config/routes.rb
Rails.application.routes.draw do
  root "churches#index"
  
  resources :users
  resources :churches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/church.rb
class Church < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  before_action :set_church, only: %i[ show edit update destroy ]
  # GET /churches or /churches.json
  def index
    @churches = Church.all
  end

  # GET /churches/1 or /churches/1.json
  def show
  end

  # GET /churches/new
  def new
    @church = Church.new
  end

  # GET /churches/1/edit
  def edit
  end

  # POST /churches or /churches.json
  def create
    @church = Church.new(church_params)

    respond_to do |format|
      if @church.save
        format.html { redirect_to church_url(@church), notice: "Church was successfully created." }
        format.json { render :show, status: :created, location: @church }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /churches/1 or /churches/1.json
  def update
    respond_to do |format|
      if @church.update(church_params)
        format.html { redirect_to church_url(@church), notice: "Church was successfully updated." }
        format.json { render :show, status: :ok, location: @church }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /churches/1 or /churches/1.json
  def destroy
    @church.destroy

    respond_to do |format|
      format.html { redirect_to churches_url, notice: "ireja deletada com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_church
      @church = Church.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def church_params
      params.require(:church).permit(:mail, :congregacao)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :mail, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/churches/_form.html.erb
<%= form_with(model: church) do |f| %>
  <% if church.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(church.errors.count, "error") %> prohibited this church from being saved:</h2>

      <ul>
        <% church.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="logo" align="center">
    <%= image_tag "canaa.png" %>
  
    <h1> RELATORIO DE ATIVIDADES <h1>
    <h2> FINANCEIRAS DIARIO - MONTESE |</h2>
    <p text-indent>
      Este formulário é de uso e preenchimento EXCLUSIVO do auxiliar de tesouraria. 
      Destinado ao controle de entradas e saídas das congregações do Ministério Canaã.
    </p>
  </div>

  <br/>

  <div class="card" align="center">
   <h3> 
      <%= f.label 'email:' %><br/>
      <%= f.text_field :mail %>
    <h3>
  </div>
  
  <br/>

  <div class="card" align="center">
   <h3>
      <%= f.label 'congregação:' %><br/>
      <%= f.text_field :congregacao %>
    </h3>
  </div>

  <br/>

  <div class="card" align="center">
    <h3>
      <%= f.label "nome do superior:" %><br/>
      <%= f.text_field "nome_superior" %>
    </h3>
  </div>

  <br/>

  <div class="card" align="center">
   <h3> 
      <%= f.label "auxiliar de tesouraria:" %><br/>
      <%= f.text_field "aux_tesouraria" %>
    </h3>
  </div>

  <br/>
  <div class="card" align="center">
    <h3>
      <%= f.label "data:" %><br/>
      <%= date_select("project", "due_date", :include_blank => true) %>
    </h3>
  </div>

  <br/>
  
  <div class="card" align="center">
    
    <h2>Dia da semana</h2><br/>
    <ul>
        <li style="list-style: none"><%= check_box_tag 'segunda-feira'%>segunda-feira</li>
        <li style="list-style: none"><%= check_box_tag 'terça-ferira' %> Quarta-feira</li>
        <li style="list-style: none"><%= check_box_tag (:id_quarta)%> Terça-feira</li>
        <li style="list-style: none"><%= check_box_tag (:id_quinra)%> Quinta-feira</li>
        <li style="list-style: none"><%= check_box_tag (:id_sexta)%> Sexta-feira</li>
        <li style="list-style: none"><%= check_box_tag (:id_sabado)%> Sabado-feira</li>
        <li style="list-style: none"><%= check_box_tag (:id_domingo)%> Domingo-feira</li>
    </ul>
  </div>

  <br/>
  
  <div class="card" align="center">
    <h3>
      <%= f.label "aceitação:" %><br/>
      <%= f.text_field "aceitacao" %>
    </h3>
  </div>

  <br/>
  
  <div class="card" align="center">
    <h3>
      <%= f.label "reconciliação:" %><br/>
      <%= f.text_field "reconciliacao" %>
    <h3>
  </div>

  <br/>
  
  <div class="card" align="center">
    <h3>
      <%= f.label "filiação:" %><br/>
      <%= f.text_field "filiacao" %>
    </h3>
  </div>

  <br/>

  <div class="card" align="center">
    <h2 >RENDA</h2 >
    <P>
      Esse campo deve ser preenchido apenas com números.  
      Lembrar de utilizar a pontuação correta para que haja compreensão devida dos valores.
    </P>
  </div>

  <br/>

  <div class="card" align="center">
    <h3>
      <%= f.label "renda do dia:" %><br/>
      <%= f.text_field "renda do dia" %>
    </h3>
  </div>

  <br/>

  <div class="card" align="center"> 
   <h3>
      <%= f.label "Renda: Culto de Adoração (Manhã)" %><br/>
      <%= f.text_field "RCAM" %>
    </h3>
  </div>

  <br/>

  <div class="card" align="center"> 
   <h3> 
      <%= f.label "Renda: Culto de Adoração (noite)" %><br/>
      <%= f.text_field "RCAN" %>
    </h3>
  </div>

  <br/>

  <div class="action" align="center">
      <%= f.submit 'Enviar Formulario' %>
  </div>
<% end %>

app/views/churches/edit.html.erb
<h1>Editing Church</h1>

<%= render 'f', church: @church %>

<%= link_to 'Ver', @church %> |
<%= link_to 'Voltar', churches_path %>

app/views/churches/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
<h1 align="center"> Seja Bem vindo </h1>
<div align="center">
  <%= image_tag "canaa.png" %>
</div>

<h1 align="center"> <%=link_to 'Cadastrar sua igreja', new_church_path %></h1>
<%= link_to 'lista de usuarios', users_path %>

app/views/churches/new.html.erb
<h1>Novo Cadastro </h1>

<%= render 'form', church: @church %>

<%= link_to 'Back', churches_path %>

app/views/churches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_church_path(@church) %> |
<%= link_to 'Back', churches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Igreja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>
                                    
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'ver', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>
  <table>
    <thead>
    <br/>
      <tr>
        <th>Nome: &nbsp; &nbsp;</th>
        <th>idade:</th>
        <th>Email:</th>
        <th>Senha:</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <td><%= user.age %></td>
          <td><%= user.mail %></td>
          <td><%= user.password %></td>
          <td><%= link_to 'ver', user %></td>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
          <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to 'Criar novo usuario', new_user_path %> &nbsp;
<%= link_to 'ver igrejas', churches_path%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>